FoodCollection/Controllers/PickupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodCollection.Data;
using FoodCollection.Models;

namespace FoodCollection.Controllers
{
    public class PickupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PickupsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pickups
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pickup.Include(p => p.BookPickup).Include(p => p.Staff);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pickups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup
                .Include(p => p.BookPickup)
                .Include(p => p.Staff)
                .FirstOrDefaultAsync(m => m.PickupId == id);
            if (pickup == null)
            {
                return NotFound();
            }

            return View(pickup);
        }

        // GET: Pickups/Create
        public IActionResult Create()
        {
            ViewData["BookPickupId"] = new SelectList(_context.BookPickup, "BookPickupId", "BookPickupId");
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId");
            return View();
        }

        // POST: Pickups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PickupId,Date,PickupStatus,BookPickupId,StaffId")] Pickup pickup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pickup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookPickupId"] = new SelectList(_context.BookPickup, "BookPickupId", "BookPickupId", pickup.BookPickupId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", pickup.StaffId);
            return View(pickup);
        }

        // GET: Pickups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup.FindAsync(id);
            if (pickup == null)
            {
                return NotFound();
            }
            ViewData["BookPickupId"] = new SelectList(_context.BookPickup, "BookPickupId", "BookPickupId", pickup.BookPickupId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", pickup.StaffId);
            return View(pickup);
        }

        // POST: Pickups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PickupId,Date,PickupStatus,BookPickupId,StaffId")] Pickup pickup)
        {
            if (id != pickup.PickupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PickupExists(pickup.PickupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookPickupId"] = new SelectList(_context.BookPickup, "BookPickupId", "BookPickupId", pickup.BookPickupId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", pickup.StaffId);
            return View(pickup);
        }

        // GET: Pickups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pickup = await _context.Pickup
                .Include(p => p.BookPickup)
                .Include(p => p.Staff)
                .FirstOrDefaultAsync(m => m.PickupId == id);
            if (pickup == null)
            {
                return NotFound();
            }

            return View(pickup);
        }

        // POST: Pickups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pickup = await _context.Pickup.FindAsync(id);
            if (pickup != null)
            {
                _context.Pickup.Remove(pickup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PickupExists(int id)
        {
            return _context.Pickup.Any(e => e.PickupId == id);
        }
    }
}

FoodCollection/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodCollection.Data;
using FoodCollection.Models;

namespace FoodCollection.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Report.Include(r => r.Staff);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.Staff)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId");
            return View();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportId,ReportTitle,Date,StaffId")] Report report)
        {
            if (ModelState.IsValid)
            {
                _context.Add(report);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", report.StaffId);
            return View(report);
        }

        // GET: Reports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Report.FindAsync(id);
            if (report == null)
            {
                return NotFound();
            }
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", report.StaffId);
            return View(report);
        }

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportId,ReportTitle,Date,StaffId")] Report report)
        {
            if (id != report.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(report);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportExists(report.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", report.StaffId);
            return View(report);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.Staff)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var report = await _context.Report.FindAsync(id);
            if (report != null)
            {
                _context.Report.Remove(report);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportExists(int id)
        {
            return _context.Report.Any(e => e.ReportId == id);
        }
    }
}

FoodCollection/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodCollection.Data;
using FoodCollection.Models;

namespace FoodCollection.Controllers
{
    public class StaffsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StaffsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Staff.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffId,Lname,Fname,Email,Phone,Addres")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffId,Lname,Fname,Email,Phone,Addres")] Staff staff)
        {
            if (id != staff.StaffId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.StaffId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            if (staff != null)
            {
                _context.Staff.Remove(staff);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.StaffId == id);
        }
    }
}

FoodCollection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodCollection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodCollection.styles.css" asp-append-version="true" />
    <style>
        body {
            padding-top: 70px;
            transition: background 0.3s, color 0.3s;
        }

        .navbar-nav .nav-link {
            transition: color 0.2s, background 0.2s;
            border-radius: 0.375rem;
        }

            .navbar-nav .nav-link:hover, .navbar-nav .nav-link:focus {
                background: rgba(67, 160, 71, 0.1);
                color: #388e3c !important;
            }

        .navbar-dark .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.active {
            font-weight: 600;
            color: #388e3c !important;
        }

        .footer-social a {
            color: #555;
            margin: 0 0.5rem;
            font-size: 1.3rem;
            transition: color 0.2s;
        }

            .footer-social a:hover {
                color: #388e3c;
            }

        .dark-mode {
            background: #181a1b !important;
            color: #e0e0e0 !important;
        }

            .dark-mode .navbar, .dark-mode .footer {
                background: #23272b !important;
            }

            .dark-mode .navbar-nav .nav-link {
                color: #e0e0e0 !important;
            }

                .dark-mode .navbar-nav .nav-link:hover {
                    background: rgba(67, 160, 71, 0.2);
                    color: #81c784 !important;
                }

            .dark-mode .footer-social a {
                color: #e0e0e0;
            }

                .dark-mode .footer-social a:hover {
                    color: #81c784;
                }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow-sm py-2 px-3">
            <div class="container-xl">
                <a class="navbar-brand d-flex align-items-center gap-2" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-basket2-fill text-success fs-3"></i>
                    <span class="fw-bold">FoodCollection</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-lg-2">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house-door-fill me-1"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="bi bi-shield-lock-fill me-1"></i> Privacy
                            </a>
                        </li>
                        @if (User.IsInRole("SuperAdmin") || User.IsInRole("Staff"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle d-flex align-items-center gap-1" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear-fill"></i> Admin
                                </a>
                                <ul class="dropdown-menu shadow border-0 rounded-3 mt-2">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Customers" asp-action="Index"><i class="bi bi-people-fill me-2"></i>Manage Customers</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Staffs" asp-action="Index"><i class="bi bi-person-badge-fill me-2"></i>Manage Staff</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="BookPickups" asp-action="Index"><i class="bi bi-truck me-2"></i>Manage BookPickup</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Appointments" asp-action="Index"><i class="bi bi-calendar-check-fill me-2"></i>Manage Appointment</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="BookPickupDetails" asp-action="Index"><i class="bi bi-list-ul me-2"></i>Manage BookPickupDetail</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="FoodItems" asp-action="Index"><i class="bi bi-basket-fill me-2"></i>Manage FoodItem</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Organizations" asp-action="Index"><i class="bi bi-building me-2"></i>Manage Organization</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Payments" asp-action="Index"><i class="bi bi-credit-card-2-front-fill me-2"></i>Manage Payment</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Pickups" asp-action="Index"><i class="bi bi-box-seam me-2"></i>Manage Pickup</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="DeliveryInfoes" asp-action="Index"><i class="bi bi-truck-flatbed me-2"></i>Manage DeliveryInfo</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="Index"><i class="bi bi-bar-chart-fill me-2"></i>Manage Report</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="RolesAdmin" asp-action="Index"><i class="bi bi-person-gear me-2"></i>RolesAdmin</a></li>
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="MyProfile">
                                    <i class="bi bi-person-circle me-1"></i> My Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="BookPickups" asp-action="MyBookings">
                                    <i class="bi bi-truck me-1"></i> My Booking
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="MyAppointments">
                                    <i class="bi bi-calendar-check-fill me-1"></i> My Appointment
                                </a>
                            </li>
                        }
                    </ul>
                    <div class="d-flex align-items-center gap-3">
                        <button id="darkModeToggle" class="btn btn-outline-secondary btn-sm" type="button" title="Toggle dark mode">
                            <i class="bi bi-moon-fill"></i>
                        </button>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-xl py-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer border-top text-muted py-2 mt-auto bg-white">
        <div class="container-xl d-flex flex-column flex-md-row justify-content-between align-items-center gap-3">
            <div>
                &copy; 2025 - FoodCollection
                &middot;
                <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-decoration-none text-success">Privacy</a>
            </div>
            <div class="footer-social">
                <a href="https://twitter.com/" target="_blank" rel="noopener" aria-label="Twitter"><i class="bi bi-twitter-x"></i></a>
                <a href="https://facebook.com/" target="_blank" rel="noopener" aria-label="Facebook"><i class="bi bi-facebook"></i></a>
                <a href="https://instagram.com/" target="_blank" rel="noopener" aria-label="Instagram"><i class="bi bi-instagram"></i></a>
                <a href="mailto:info@foodcollection.org" aria-label="Email"><i class="bi bi-envelope-fill"></i></a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        // Smooth scrolling for anchor links
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    e.preventDefault();
                    window.scrollTo({
                        top: target.offsetTop - 70,
                        behavior: 'smooth'
                    });
                }
            });
        });

        // Dark mode toggle
        const darkModeToggle = document.getElementById('darkModeToggle');
        const body = document.body;
        const darkModeKey = 'fc_dark_mode';
        function setDarkMode(on) {
            if (on) {
                body.classList.add('dark-mode');
                darkModeToggle.innerHTML = '<i class="bi bi-brightness-high-fill"></i>';
            } else {
                body.classList.remove('dark-mode');
                darkModeToggle.innerHTML = '<i class="bi bi-moon-fill"></i>';
            }
        }
        // Load preference
        setDarkMode(localStorage.getItem(darkModeKey) === '1');
        darkModeToggle.addEventListener('click', () => {
            const isDark = !body.classList.contains('dark-mode');
            setDarkMode(isDark);
            localStorage.setItem(darkModeKey, isDark ? '1' : '0');
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>